
package view;

import java.sql.SQLException;
import controller.TabelaUsuarioControle;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.Usuario;

public class TelaControleUsuarios extends javax.swing.JFrame {

    public TelaControleUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MarcadoresCadastro = new javax.swing.ButtonGroup();
        botaoVoltar = new javax.swing.JButton();
        botaoDeletarConta = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaUsuarios = new javax.swing.JTable();
        imagemControleUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1533, 887));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botaoVoltar.setContentAreaFilled(false);
        botaoVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoVoltarMouseClicked(evt);
            }
        });
        getContentPane().add(botaoVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 620, 100, 30));

        botaoDeletarConta.setContentAreaFilled(false);
        botaoDeletarConta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoDeletarConta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoDeletarContaMouseClicked(evt);
            }
        });
        getContentPane().add(botaoDeletarConta, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 200, 250, 30));

        TabelaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Usuario", "Senha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TabelaUsuarios.getTableHeader().setReorderingAllowed(false);
        TabelaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaUsuarios);
        if (TabelaUsuarios.getColumnModel().getColumnCount() > 0) {
            TabelaUsuarios.getColumnModel().getColumn(0).setResizable(false);
            TabelaUsuarios.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 700, 530));

        imagemControleUsuario.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        imagemControleUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/TelaControleDeUsuarios.jpg"))); // NOI18N
        imagemControleUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        imagemControleUsuario.setMaximumSize(new java.awt.Dimension(1280, 720));
        imagemControleUsuario.setMinimumSize(new java.awt.Dimension(1280, 720));
        imagemControleUsuario.setPreferredSize(new java.awt.Dimension(1600, 900));
        getContentPane().add(imagemControleUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, 0, 1920, 870));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoVoltarMouseClicked
        //Comandos para retornar para a tela principal de admin
        this.toBack();
        setVisible(false);
        TelaAdmin telaDeAdmin = new TelaAdmin();
        telaDeAdmin.setVisible(true);
        telaDeAdmin.toFront();
    }//GEN-LAST:event_botaoVoltarMouseClicked

    private void botaoDeletarContaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoDeletarContaMouseClicked
        //Remove a fileira de usuario (Implementar junto com o banco de dados posteriormente
        // a função de ao apagar o usuario da tabela também o deletá-lo do banco de dados)
        int fileiraSelecionada = TabelaUsuarios.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)TabelaUsuarios.getModel();
        model.removeRow(fileiraSelecionada);
    }//GEN-LAST:event_botaoDeletarContaMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            mostrarUsuario();
        } catch (SQLException ex) {
            Logger.getLogger(TelaControleUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void TabelaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaUsuariosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TabelaUsuariosMouseClicked

        public void mostrarUsuario() throws SQLException {
        TabelaUsuarioControle controle = new TabelaUsuarioControle();    
        ArrayList<Usuario> lista = controle.listaUsuarios();
        DefaultTableModel tabelaUsuarios = (DefaultTableModel)TabelaUsuarios.getModel();
        Object [] fileira = new Object [2];
        for (int i = 0; i<lista.size();i++) {
            fileira[0] = lista.get(i).getNome();
            fileira[1] = lista.get(i).getSenha();
            tabelaUsuarios.addRow(fileira);
        }
        
    }
    public JTable getTabelaUsuarios() {
        return TabelaUsuarios;
    }

    public void setTabelaUsuarios(JTable TabelaUsuarios) {
        this.TabelaUsuarios = TabelaUsuarios;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaControleUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaControleUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaControleUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaControleUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaControleUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup MarcadoresCadastro;
    private javax.swing.JTable TabelaUsuarios;
    private javax.swing.JToggleButton botaoDeletarConta;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JLabel imagemControleUsuario;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
